// export default function SignatoriesSection() {
//     // Sample signatory data - in a real app this would come from an API
//     const signatories = [
//       "2LK",
//       "21st Brands",
//       "21% Studio",
//       "3 Sided Cube",
//       "A2 Design",
//       "AEIOU",
//       "Alias Aligned",
//       "Alpha Websites",
//       "APRE - A Creative",
//       "Archetype Studio",
//       "Active Medial",
//       "Agile",
//       "Airside",
//       "Alchemystic",
//       "Almodóvar Design Agency",
//       "Aloof Design",
//       "Altern Design Ltd",
//       "Alan Dempsey",
//       "Alexander Boxill",
//       "Alexander Kent",
//       "Alexander Lam Studio",
//       "Alexander Tochilovsky",
//       "Alexis Sommer",
//       "Almo Sartori",
//       "Aloof Design",
//       "Andrew Carr",
//       "Andy Fletcher",
//       "Andy Potts",
//       "Anja Dohse",
//       "Annabelle Vella",
//       "Antidote",
//       "Applied Works",
//       "Archetype Associates",
//       "Archetype Studio",
//       "Ariel Aguilera",
//       "Avery & Brown",
//       "BA (Hons) Graphic Design",
//       "BA (Hons) Graphic Art",
//       "Arts University",
//       "Bournemouth",
//       "Barnbrook Design",
//       "Bergman School of Art",
//       "Beatrice Lessi",
//       "Ben Chatfield",
//       "Barbara Chandler",
//       "Barbara Chandler",
//       "Barbara Chandler",
//       "Barth Worlds",
//       "Baxter & Bailey",
//       "Baxter & Bailey",
//       "Beau",
//       "Ben Chatfield",
//       "Ben Chatfield",
//       "Ben Jessop",
//       "Blackstock Limited",
//       "Blackstock Limited",
//       "Brita Design Office",
//       "Bill Bragg",
//       "Bill Bragg",
//       "Big Motive",
//       "Big Motive",
//       "Big Motive",
//     ]
  
//     // Add more signatories to demonstrate the full layout
//     const allSignatories = [
//       ...signatories,
//       "Bloomsbury Innovation Lab",
//       "Design by Mondial",
//       "Francis Rowland",
//       "Isadora",
//       "Morphography Studio",
//       "Olivia Studio Ltd",
//       "Sheffield Hallam University",
//       "The Manufacturing",
//       "Blok",
//       "Design Council",
//       "Frankie Ratford",
//       "Jack Bancroft",
//       "Moritz",
//       "Olivia Studio Ltd",
//       "Simons Coop",
//       "Technology Centre",
//       "Blue State Digital",
//       "Design for Joy",
//       "Future Generations at",
//       "James Aldred",
//       "Moritz Cai Studio",
//       "Olive Kittredge",
//       "Social Change",
//       "ThinkUp",
//       "Boyles & Plants",
//       "Design for Joy",
//       "Future Generations at",
//       "James Aldred",
//       "Moritz Cai Studio",
//       "Olive Kittredge",
//       "Social Change",
//       "ThinkUp",
//       "Brand Sympathy",
//       "Design Indaba",
//       "Glow Collective",
//       "James Greenfield",
//       "Moss Editions Ltd",
//       "Oli Kellett",
//       "Sophie Blackmore",
//       "Thirteen05 Consulting",
//       "Brandalism",
//       "Design Thinc",
//       "Fullstop",
//       "James Greenfield",
//       "Moss Editions Ltd",
//       "Oli Kellett",
//       "Sophie Blackmore",
//       "Thirteen05 Consulting",
//       "Brandalism",
//       "Design Thinc",
//       "Fullstop Ltd",
//       "James Greenfield",
//       "Moss Editions Ltd",
//       "Oli Kellett",
//       "Sophie Blackmore",
//       "Thirteen05 Consulting",
//       "Brandalism",
//       "Design Thinc",
//       "Fullstop Ltd",
//       "James Greenfield",
//       "Moss Editions Ltd",
//       "Oli Kellett",
//       "Sophie Blackmore",
//       "Thirteen05 Consulting",
//       "ACRE - A Creative",
//       "Design Works Ltd",
//       "Future Brand",
//       "James Greenfield",
//       "Moss Editions Ltd",
//       "Oli Kellett",
//       "Sophie Blackmore",
//       "Thirteen05 Consulting",
//       "Active Medial",
//       "Bright Signals Ltd",
//       "Gemma Griffith",
//       "GH Creative",
//       "INTERROBANG",
//       "ORCA",
//       "Sniff Design",
//       "Thane Reach",
//       "Agile",
//       "Bright Signals Ltd",
//       "Gemma Griffith",
//       "Green Nest Ltd",
//       "Martin Hopkins",
//       "Odin",
//       "Sniff Design",
//       "The Framestore & Co",
//       "Airside",
//       "Bright Signals Ltd",
//       "Gemma Griffith",
//       "Green Nest Ltd",
//       "Martin Hopkins",
//       "Odin",
//       "Sniff Design",
//       "The Framestore & Co",
//     ]
  
//     return (
//       <div>
//         <section className="bg-black py-16 px-4 md:px-12">
//           <div className="max-w-7xl mx-auto">
//             {/* Top Left Corner - Count and Header */}
//             <div className="mb-12">
//               <div className="space-y-2">
//                 <h2 className="text-white text-4xl md:text-5xl lg:text-6xl font-light">#513</h2>
//                 <div className="flex items-center gap-2">
//                   <span className="text-white text-sm md:text-base">Signatories and counting in</span>
//                   <span className="bg-[#FF5630] text-white text-xs px-2 py-1 rounded font-medium">DI UK</span>
//                 </div>
//               </div>
//             </div>
  
//             {/* Full Width Signatories List */}
//             <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-x-6 gap-y-1 text-sm">
//               {allSignatories.map((signatory, index) => (
//                 <div key={index} className="text-white hover:text-gray-300 transition-colors duration-200 py-1">
//                   {signatory}
//                 </div>
//               ))}
//             </div>
//           </div>
//         </section>
  
//         {/* Fixed Bottom-Right Buttons */}
        
//       </div>
//     )
//   }
  "use client"

import { useState, useEffect } from "react"

export default function Component() {
  const [count, setCount] = useState(0)

  // Animate the count up to 513
  useEffect(() => {
    const timer = setInterval(() => {
      setCount((prev) => {
        if (prev < 513) {
          return prev + Math.ceil((513 - prev) / 10)
        }
        return 513
      })
    }, 50)

    return () => clearInterval(timer)
  }, [])

  const signatories = [
    "21:37",
    "Elementary Innovation Lab",
    "Design by Monkee",
    "Francis Rowland",
    "techies",
    "Marketingbiography Studio",
    "Choice Studio Ltd",
    "Sheffield Hallam University",
    "The Manufacturing",
    "21K School",
    "Eliot Grayson",
    "Design by Monkee",
    "Carton Design",
    "Jemma Maccabe",
    "Meld",
    "Chroma",
    "Simon Collison",
    "Technology Centre",
    "2Y",
    "Eliot Grayson",
    "Design by Monkee",
    "Carton Design",
    "Jemma Maccabe",
    "Meld",
    "Chroma",
    "Simon Collison",
    "The Allotment",
    "400",
    "Bold Studio",
    "Design for Joy",
    "Future transcendent at",
    "James Kontact",
    "Mar Alo Co. Studio",
    "Chris Kensington",
    "Social Change",
    "ThinkCo",
    "A-B",
    "Bold Studio",
    "Design for Joy",
    "Future transcendent at",
    "James Kontact",
    "Mar Alo Co. Studio",
    "Chris Kensington",
    "Social Change",
    "ThinkCo",
    "A-Side",
    "Bold Studio",
    "Design for Joy",
    "Future transcendent at",
    "James Kontact",
    "Mar Alo Co. Studio",
    "Chris Kensington",
    "Social Change",
    "ThinkCo",
    "A-Side Channel",
    "Bold Studio",
    "Design for Joy",
    "Future transcendent at",
    "James Kontact",
    "Mar Alo Co. Studio",
    "Chris Kensington",
    "Social Change",
    "ThinkCo",
    "Abbie Williams",
    "Pentagram",
    "Design Thinks",
    "Future Solves",
    "jen lewis creative",
    "Marlon Radio",
    "Crawford Creative",
    "Sophie Thomas",
    "Thomas Bendel Cassidy",
    "ABC",
    "Bespoke",
    "Design Thinks",
    "Future Solves",
    "jen lewis creative",
    "Marlon Radio",
    "Crawford Creative",
    "Sophie Thomas",
    "Thomas Bendel",
    "Abduzeedo",
    "Bespoke",
    "Design Thinks",
    "Future Solves",
    "jen lewis creative",
    "Marlon Radio",
    "Crawford Creative",
    "Sophie Thomas",
    "Thomas Bendel",
    "Endeavour Ltd",
    "Bright Signals Design at",
    "Ditto Macdonald",
    "G R Moore Limited",
    "Jason Mesut",
    "MENTO ROSENTO",
    "Creatively",
    "Spotless",
    "Thoughtform",
    "Agile Minds",
    "Bright Signals Design at",
    "Ditto Macdonald",
    "G R Moore Limited",
    "Jason Mesut",
    "MENTO ROSENTO",
    "Creatively",
    "Spotless",
    "Thoughtform",
    "Agile Minds",
    "Bright Signals Design at",
    "Ditto Macdonald",
    "G R Moore Limited",
    "Jason Mesut",
    "MENTO ROSENTO",
    "Creatively",
    "Spotless",
    "Thoughtform",
    "Aiden Kelly",
    "Business Ideas",
    "Ditto Macdonald",
    "Gabriel Woo",
    "Jez Francis",
    "Martin Price",
    "Other Valley",
    "Stella Gasseling",
    "True Berlinese",
    "Alexander Hanson Agency",
    "Business Ideas",
    "Ditto Macdonald",
    "Gabriel Woo",
    "Jez Francis",
    "Martin Price",
    "Other Valley",
    "Stella Gasseling",
    "True Berlinese",
    "Alexis Design",
    "Cartridge",
    "DJ Emma Powell",
    "Genuinely Generous",
    "John Boardman",
    "Martin Price",
    "Other Valley",
    "Stella Gasseling",
    "True Berlinese",
    "Alexis Design",
    "Cartridge",
    "DJ Emma Powell",
    "Genuinely Generous",
    "John Boardman",
    "Martin Price",
    "Other Valley",
    "Stella Gasseling",
    "True Berlinese",
    "Alison Haigh Ltd",
    "Cartridge",
    "DJ Emma Powell",
    "Genuinely Generous",
    "John Boardman",
    "Martin Price",
    "Other Valley",
    "Stella Gasseling",
    "True Berlinese",
    "Alison Haigh Ltd",
    "Cartridge",
    "DJ Emma Powell",
    "Genuinely Generous",
    "John Boardman",
    "Martin Price",
    "Other Valley",
    "Stella Gasseling",
    "True Berlinese",
    "Alternative Lifestyle",
    "Cartridge",
    "DJ Emma Powell",
    "Genuinely Generous",
    "John Boardman",
    "Martin Price",
    "Other Valley",
    "Stella Gasseling",
    "True Berlinese",
    "Alternative Lifestyle",
    "Cartridge",
    "DJ Emma Powell",
    "Genuinely Generous",
    "John Boardman",
    "Martin Price",
    "Other Valley",
    "Stella Gasseling",
    "True Berlinese",
    "Alternative Lifestyle",
    "Cartridge",
    "DJ Emma Powell",
    "Genuinely Generous",
    "John Boardman",
    "Martin Price",
    "Other Valley",
    "Stella Gasseling",
    "True Berlinese",
    "Alweb Summer",
    "Cherry Anderson",
    "Edmundson",
    "Gear Customs",
    "Justine Wynyard",
    "Max Foster",
    "Pixel Fridge LTD",
    "Studio Gallant",
    "Taxi Degrees Studio",
    "Anna Baines",
    "Psychedelic Breakfast",
    "Edmundson",
    "Gear Customs",
    "Justine Wynyard",
    "Max Foster",
    "Pixel Fridge LTD",
    "Studio Gallant",
    "Taxi Degrees Studio",
    "Anna Baines",
    "Psychedelic Breakfast",
    "Edmundson",
    "Gear Customs",
    "Justine Wynyard",
    "Max Foster",
    "Pixel Fridge LTD",
    "Studio Gallant",
    "Taxi Degrees Studio",
    "Andrew Carr",
    "Chris O'Neal",
    "Eleven",
    "Good Stuff Creative",
    "Kaleido Grath",
    "Micha Neumann",
    "Pointum Chechan",
    "Studio Markmento",
    "Unbound Studio",
    "Andy Potts",
    "Cash Flow Design",
    "Eleven",
    "Good Stuff Creative",
    "Kaleido Grath",
    "Micha Neumann",
    "Pointum Chechan",
    "Studio Markmento",
    "Unbound Studio",
    "Andy Potts",
    "Cash Flow Design",
    "Eleven",
    "Good Stuff Creative",
    "Kaleido Grath",
    "Micha Neumann",
    "Pointum Chechan",
    "Studio Markmento",
    "Unbound Studio",
    "Anja Kober",
    "Chris Lewis",
    "Ellis Nelson Design",
    "Goodwin Henderson",
    "Katherine Kautzner",
    "Michael Normington",
    "University of Brighton",
    "Studio Outrid",
    "URGE Collective",
    "Annabelle Harty",
    "Chris Lewis",
    "Ellis Nelson Design",
    "Goodwin Henderson",
    "Katherine Kautzner",
    "Michael Normington",
    "University of Brighton",
    "Studio Outrid",
    "URGE Collective",
    "Annabelle Harty",
    "Chris Lewis",
    "Ellis Nelson Design",
    "Goodwin Henderson",
    "Katherine Kautzner",
    "Michael Normington",
    "University of Brighton",
    "Studio Outrid",
    "URGE Collective",
    "Applied Works",
    "Christa Lark",
    "EMMA BRITTAIN",
    "Great Creative",
    "Kenny Heard",
    "Minna Takala",
    "Product for Net Zero",
    "Studio Technical Nature",
    "Vicky Lofthouse",
    "Archetype Modernist",
    "Christa Lark",
    "EMMA BRITTAIN",
    "Great Creative",
    "Kenny Heard",
    "Minna Takala",
    "Product for Net Zero",
    "Studio Technical Nature",
    "Vicky Lofthouse",
    "Archetype Modernist",
    "Christa Lark",
    "EMMA BRITTAIN",
    "Great Creative",
    "Kenny Heard",
    "Minna Takala",
    "Product for Net Zero",
    "Studio Technical Nature",
    "Vicky Lofthouse",
    "Army",
    "Competent Studio",
    "Ernest Organics",
    "Great Orbit Digital",
    "Kim Ward",
    "Moodboard",
    "Rahul Anand",
    "Submarine",
    "VINO NINE",
    "Army",
    "Competent Studio",
    "Ernest Organics",
    "Great Orbit Digital",
    "Kim Ward",
    "Moodboard",
    "Rahul Anand",
    "Submarine",
    "VINO NINE",
    "Art & Bauer",
    "Competent Studio",
    "Ernest Organics",
    "Great Orbit Digital",
    "Kim Ward",
    "Moodboard",
    "Rahul Anand",
    "Submarine",
    "VINO NINE",
    "Authentic Brands for",
    "Competent Studio",
    "Ernest Organics",
    "Great Orbit Digital",
    "Kim Ward",
    "Moodboard",
    "Rahul Anand",
    "Submarine",
    "VINO NINE",
    "Sustainable Futures at",
    "Confuse",
    "Ethos",
    "GreatRights",
    "KULVENDROVE",
    "MONOAKTIF",
    "Redisigned Landscape",
    "Susanna Edwards",
    "Vu Grays",
    "AIA Sydney",
    "Creative at Osento",
    "Ethos Design",
    "Halo",
    "Kyle Bice",
    "Muddy Machines",
    "Redisigned Landscape",
    "Susanna Edwards",
    "Vu Grays",
    "AIA Sydney",
    "Creative at Osento",
    "Ethos Design",
    "Halo",
    "Kyle Bice",
    "Muddy Machines",
    "Redisigned Landscape",
    "Susanna Edwards",
    "Vu Grays",
    "BA Graphic Design at",
    "Creative Conscience",
    "Eva Politis",
    "Hannah Insight",
    "Laura Beechcroft",
    "Mute Pictures Studio",
    "Rio Creations",
    "Tate",
    "We About This Ltd",
    "Kingston University of Art",
    "Creative Conscience",
    "Eva Politis",
    "Hannah Insight",
    "Laura Beechcroft",
    "Mute Pictures Studio",
    "Rio Creations",
    "Tate",
    "We About This Ltd",
    "BA Graphic Design at",
    "Creative Conscience",
    "Eva Politis",
    "Hannah Insight",
    "Laura Beechcroft",
    "Mute Pictures Studio",
    "Rio Creations",
    "Tate",
    "We About This Ltd",
    "Banfield Design LTD",
    "Creative Conscience",
    "F VERZANO",
    "Harrison Brands Ltd",
    "Laura Dawson",
    "Net Positive",
    "Ronny Cutler",
    "TAWKIT",
    "White West Limited",
    "Banfield Design LTD",
    "Creative Conscience",
    "F VERZANO",
    "Harrison Brands Ltd",
    "Laura Dawson",
    "Net Positive",
    "Ronny Cutler",
    "TAWKIT",
    "White West Limited",
    "Banfield Design LTD",
    "Creative Conscience",
    "F VERZANO",
    "Harrison Brands Ltd",
    "Laura Dawson",
    "Net Positive",
    "Ronny Cutler",
    "TAWKIT",
    "White West Limited",
    "Basalt Works",
    "Dytton Ltd",
    "FeedBack",
    "Hey Lani",
    "LJ Creative Studio",
    "Neutral",
    "Ruth Wassermann Ltd",
    "Liminal",
    "Working with Joe Ltd",
    "Basalt Works",
    "Dytton Ltd",
    "FeedBack",
    "Hey Lani",
    "LJ Creative Studio",
    "Neutral",
    "Ruth Wassermann Ltd",
    "Liminal",
    "Working with Joe Ltd",
    "Basalt Works",
    "Dytton Ltd",
    "FeedBack",
    "Hey Lani",
    "LJ Creative Studio",
    "Neutral",
    "Ruth Wassermann Ltd",
    "Liminal",
    "Working with Joe Ltd",
    "Bauer & Turner",
    "D Squared Product",
    "Fern and Far",
    "Hyland",
    "Lubo Creative",
    "New Atomics",
    "Samuel Merchant",
    "The Art and Design",
    "atommy",
    "Bauer & Turner",
    "D Squared Product",
    "Fern and Far",
    "Hyland",
    "Lubo Creative",
    "New Atomics",
    "Samuel Merchant",
    "The Art and Design",
    "atommy",
    "Bauer & Turner",
    "D Squared Product",
    "Fern and Far",
    "Hyland",
    "Lubo Creative",
    "New Atomics",
    "Samuel Merchant",
    "The Art and Design",
    "atommy",
    "Bea Jesso",
    "Dave Crossland",
    "Fiona Watkins Design",
    "HOUSE OF HACKNEY",
    "Lucy Watkins",
    "Nuggets & Chips",
    "Sense",
    "The Creative Bloc",
    "gavin lucan",
    "Bea Jesso",
    "Dave Crossland",
    "Fiona Watkins Design",
    "HOUSE OF HACKNEY",
    "Lucy Watkins",
    "Nuggets & Chips",
    "Sense",
    "The Creative Bloc",
    "gavin lucan",
    "Bea Jesso",
    "Dave Crossland",
    "Fiona Watkins Design",
    "HOUSE OF HACKNEY",
    "Lucy Watkins",
    "Nuggets & Chips",
    "Sense",
    "The Creative Bloc",
    "gavin lucan",
    "Bea Jesso",
    "Dave Crossland",
    "Fiona Watkins Design",
    "HOUSE OF HACKNEY",
    "Lucy Watkins",
    "Nuggets & Chips",
    "Sense",
    "The Creative Bloc",
    "gavin lucan",
    "Bea Jesso",
    "Dave Crossland",
    "Fiona Watkins Design",
    "HOUSE OF HACKNEY",
    "Lucy Watkins",
    "Nuggets & Chips",
    "Sense",
    "The Creative Bloc",
    "gavin lucan",
    "Bea Jesso",
    "Dave Crossland",
    "Fiona Watkins Design",
    "HOUSE OF HACKNEY",
    "Lucy Watkins",
    "Nuggets & Chips",
    "Sense",
    "The Creative Bloc",
    "gavin lucan",
  ]

  return (
    <div className="min-h-screen bg-black text-white p-6 md:p-8 lg:p-12">
      <div className="max-w-7xl mx-auto">
        {/* Header Section */}
        <div className="mb-12">
          <h1 className="text-6xl md:text-7xl lg:text-8xl font-light mb-2">#{count}</h1>
          <div className="flex items-center gap-2 text-2xl">
            <span>Signatories and counting in</span>
            <span className="bg-[#FF6340] text-white px-2 py-1 rounded text-sm font-medium">D&A</span>
          </div>
        </div>

        {/* Signatories Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 gap-x-8 gap-y-1 text-sm leading-relaxed">
          {signatories.map((signatory, index) => (
            <div key={index} className="text-white/90 hover:text-white transition-colors duration-200">
              {signatory}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
